### ISSUE TITLE
Missing Directory

### ISSUE THREAD

**Issue by joshuajmlee** [jbarguil/raspberrypi-get-ip#1]
When I installed msmtp msmtp-mta, there was no /etc/msmtprc directory for me to edit any config files in. Do you know where this might have been created?

**Comment by jbarguil** [comment]
Apparently my guide is outdated and config file path is `~/.msmtprc` or `$XDG_CONFIG_HOME/msmtp/config` since version 1.8.6:

[Source 1](https://wiki.archlinux.org/title/msmtp)
[Source 2](https://marlam.de/msmtp/msmtp.html#:~:text=The%20default%20user%20configuration%20file,changed%20by%20command%20line%20options.)
